[package]
name = "concat_const"
authors = ["Dmitry Rodionov <gh@rdmtr.com>"]
description = "const `&[u8]` and `&str` concatenation"
version = "0.1.0"
license = "MIT OR Apache-2.0"
edition = "2021"

[dependencies]
